### ISSUE TITLE
be generic over the serde implementation

### ISSUE THREAD

**Issue by jordens** [quartiq/miniconf#103]
* [ ] it doesn't need to be JSON for the values
* [x] the path items for array indices could be parsed via some other means, e.g. `str::parse::<usize>()` (#105)

**Comment by ryan-summers** [comment]
I believe it should be relatively easy to make a `Miniconf` impl generic over a `Serializer` or `Deserializer` that we call into directly.
We could easily also provide defaults for serde_json_core as well if desired.

The indices should definitely be `FromStr` parseable.

**Comment by jordens** [comment]
or even just `set_path()` generic over `Deserializer` and `get_path` generic over `Serializer`.

**Comment by ryan-summers** [comment]
Hmm... One annoyance is that `serde_json_core` does not expose the `Serializer` and `Deserializer` via the public API. That being said, I don't see why we couldn't make a PR to add that support. The user would be responsible for constructing the serializer/deserializer from a buffer, but that's no big ask.

**Comment by jordens** [comment]
Ack. We can still expose that easier serde-json-core API that does that for the user in the same way we expose `set()` that splits the path for the user before calling `set_path()`.
