### ISSUE TITLE
be generic over the path format and separator

### ISSUE THREAD

**Issue by jordens** [quartiq/miniconf#104]
~No real need to enforce a `Peekable<Split<char>>`.
Maybe https://docs.rs/itertools/latest/itertools/trait.PeekingNext.html is enough.~

* [x] `get_path()` and `set_path()` are now (with #105) generic over the path format and separator.
* [ ] `next_path` and `metadata()` need redesign to make them agnostic.

**Comment by ryan-summers** [comment]
There are a few places where a separator is employed:
1. During derivation to construct setting lookup paths
2. During `Miniconf::get()` and `Miniconf::set()` default implementations.
3. In default `miniconf::Array` and `[T; N]` implementations

It seems like the macro could (quite easily) expose a new attribute to specify the separator:
```rust
#[derive(Miniconf)]
#[miniconf(separator=':')]
struct Settings {
   // ...
}
```

During code-gen, we could implement an overriden `get()` and `set()` function as well as updated path generation function. I'm not sure how we could fix up the default implementation for `array` - perhaps the separator could be passed into the `recurse_paths` function.

**Comment by jordens** [comment]
Or maybe `next_path` can be restructured to return an iterator over path parts. Then the user (or `iter_paths()`) can join each path.
