### ISSUE TITLE
Interference/problems with miniconf and other mqtt paths

### ISSUE THREAD

**Issue by nkrackow** [quartiq/miniconf#142]
Using the latest master branch with eg. Stabilizer dual-iir (aka using vanilla Stabilizer master branch, just changing the miniconf dep to the github master and minimq to 0.6.2) leads to the following issues:

Miniconf seems to be confused with messages that are not intended for it. I get the following debug prints:
```
INFO - Starting
INFO - EUI48: 80-34-28-1f-59-65
INFO - setup() complete
WARN - Network link DOWN
WARN - Network link UP
INFO - MQTT connected, subscribing to settings
INFO - Unknown Miniconf command: /alive
INFO - Unknown Miniconf command: /telemetry
```

If I publish onto a miniconf setting I get `WARN - Failed to build response message`.

The miniconf settings are applied at the device and I also see the mqtt messages like `/alive` on the host.

**Comment by jordens** [comment]
https://github.com/quartiq/miniconf/blob/8be449dcd9be7c838720c21223dac0841595dd26/src/mqtt_client/mod.rs#L324

**Comment by ryan-summers** [comment]
I think this may be a knocking effect of the new get/set commands and the telemetry prefixes conflicting and I'm not sure this is a defect in miniconf. Perhaps we need to think more about how the matt tree should look...

**Comment by nkrackow** [comment]
Well but we used to always get the response if the setting or the path are invalid which was very helpful. And as it is it always wants to send this but doesn't have a response topic.

**Comment by jordens** [comment]
Might be useful for debugging but it's not useful with the miniconf client nor required by the miniconf protocol. Hence it's also not tested or maintained. Let's get rid of it.
The recommendation is to set a response topic (use the miniconf client)

**Comment by ryan-summers** [comment]
Agreed with @jordens here. The `ResponseTopic` will provide failure information such as an invalid path or setting. If there's no `ResponseTopic` specified, I don't think we should be doing anything.
