### ISSUE TITLE
MQTT `list` may provide paths that are absent at runtime

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/miniconf#194]
If a setting is an `Option`, and thus run-time dependent, it will still be provided in the `list` output of the MQTT client.

This could be acceptable, but we should document it. Otherwise, we should update `list` to use the current settings structure to traverse the present paths instead of all possible paths.

**Comment by jordens** [comment]
I think it's ok to include absent paths. But it should indeed be documented.
