### ISSUE TITLE
Remove the concept of "committing" settings in favor of terminal updates

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/miniconf#26]
Instead of "committing" staged settings into the active settings, @jordens and I came to the conclusion that we likely want to instead:
* Disallow setting the same value from different scopes (https://github.com/quartiq/miniconf/issues/18)
* Inform the application of settings updates whenever a new value arrives

This achieves the same outcome (atomic updates of similar settings) via a simpler mechanism (multiple settings configured simultaneously) and eliminates the strangeness of the `commit` topic.

**Comment by jordens** [comment]
Just confirming a design decision: arrays are only atomic through encapsulation in an atomic `struct`.
(correct? @ryan-summers).

**Comment by ryan-summers** [comment]
Correct - arrays may not be set entirely at once and will always defer down to their member elements (unless wrapped in MinconfAtomic, as you note)
