### ISSUE TITLE
Make the MQTT response machine readable and formalize it

### ISSUE THREAD

**Issue by jordens** [quartiq/miniconf#32]
https://github.com/quartiq/miniconf/blob/1f0264107cff3be8055d57e6a752522b9a28ab0e/src/mqtt_interface.rs#L166-L180

it would be better if we formalize the miniconf response to be machine readable JSON. That would allow the host layer to parse it. The response should probably just be the serialization of that `Result<T>`.

That may also be a useful approach to return the result of potential future validation hooks.

**Comment by ryan-summers** [comment]
Closing. This is now the responsibility of lower layers and is application-specific.
