### ISSUE TITLE
Accept minimq messages rather than owning the client

### ISSUE THREAD

**Issue by dnadlinger** [quartiq/miniconf#35]
In many `miniconf` applications, it might be desirable to expose an MQTT interface beyond the auto-generated settings interface (e.g. to trigger sampling of some measurements, query fast-changing status information, etc.).

Currently, `MqttInterface` takes over the `minimq::MqttClient`, so this isn't possible.

The easiest option would probably be to have a `try_process` method instead that the client code can call from the MqttClient message callback, so messages outside the miniconf tree can be handled by application-specific code.

**Comment by dnadlinger** [comment]
(This also avoids piping all the network stack/… through MqttInterface, which is a bit clunky.)

**Comment by dnadlinger** [comment]
Okay, actually it doesn't remove the need for all the network stack type parameters, as there is no general (non-generic, or only in the error type) MqttInterface trait.

In that instance, we might as well add an extra callback parameter to `update` to which unknown messages are forwarded.

**Comment by ryan-summers** [comment]
Just to elaborate - there's also a `miniconf::MqttInterface::client()` function which accepts a closure. That closure is provided the MQTT client object, so you can still perform arbitrary actions directly with the underlying client. This API was intended to allow these types of use-cases that you're referring to.

**Comment by dnadlinger** [comment]
But what I need to do is handle messages other than the ones expected by Miniconf. How would that work with the `client()` API?

**Comment by ryan-summers** [comment]
That's a valid point - I'll have to think about the architecture here to see if that would make sense

**Comment by ryan-summers** [comment]
The more I've thought about this, the more I'm coming under the opinion that owning the client is the wrong API. It makes it really difficult to use MQTT for anything besides miniconf.

I'm going to work on a refactor to pull MQTT ownership out of miniconf. Theoretically, miniconf doesn't even depend on MQTT - it just depends on some topic-data pairing that serializes data with JSON.
