### ISSUE TITLE
Settings republish events register as updated settings

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/miniconf#71]
When miniconf republishes settings, it registers the message that it has published as inbound change requests. This causes it to generate settings update events for all settings.

**Comment by jordens** [comment]
Yeah. We should probably not just stall incoming messages but actually discard them. Or mark them with a property as application-originating?

**Comment by ryan-summers** [comment]
We could theoretically append some `CorrelationData` indicating that they are republished messages.

While we can modify the Miniconf state machine to just reject/ignore any inbound settings configurations while doing republishing, this doens't solve the problem completely since we would transition state after republishing the last setting, which then causes us to re-receive it. I think correlation data is likely the best approach.
