### ISSUE TITLE
use actions-rs/clippy-check in CI and adress clippy lints

### ISSUE THREAD

**Issue by jordens** [quartiq/miniconf#78]
Like on `booster` or `stabilizer`.
Now the clippy lints just disapper in the run logs and nobody looks at them.
There are many good lints to be adressed.
https://github.com/quartiq/miniconf/runs/5052952370?check_suite_focus=true

**Comment by ryan-summers** [comment]
Agreed - I was under the assumption that clippy lints were required to be clear to pass, so this is obviously a bug. Thanks for pointing it out.
