### ISSUE TITLE
Update documentation around `handled_update`

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/miniconf#93]
Currently `handled_update`'s examples seem to indicate that the user is responsible for copying the new settings into the current settings, but this isn't explicitly stated anywhere.

Update documentation to make it clear that the new settings must be copied to the old.

Alternatively, if the handler provides an `Ok()` result, we could perform this copy automatically internally.

**Comment by jordens** [comment]
superseded by #198 and #199
